# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: 
google_analytics: 
title: "title line"

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Hack the box write-ups

description: Hack the box write-ups
author: 
  name: db-d2
  github: db-d2
  linkedin: david-benson-dmb2262

categories_path: categories.html
tags_path: tags.html

# set it as url of an image
sidebar_background_image: /bg.jpg

BASE_PATH:

plugins:
  - jekyll-paginate
